# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SliderTool
                                 A QGIS plugin
 Go through all bands quickly.  Useful for manual quality checks.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-18
        copyright            : (C) 2026 by Swapnil Goel, Pixxel
        email                : swapnilgoel2704@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SliderTool class from file SliderTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Slider_Tool import SliderTool
    return SliderTool(iface)
